/**
 * 設定管理サーバー
 * 
 * ダッシュボードからの設定保存を受け付け、
 * .env.api と GitHub Secrets に反映する
 */

import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const PORT = 3001;
const PROJECT_ROOT = path.join(__dirname, '..');
const ENV_FILE = path.join(PROJECT_ROOT, '.env.api');

// 設定項目の定義
const SECRET_KEYS = [
  // X (Twitter) 認証
  'X_USERNAME',
  'X_PASSWORD',
  'X_API_KEY',
  'X_API_SECRET',
  'X_ACCESS_TOKEN',
  'X_ACCESS_SECRET',
  'X_BEARER_TOKEN',
  // AI API
  'OPENAI_API_KEY',
  'GROK_API_KEY',
  'GOOGLE_AI_API_KEY',
];

// .env.api を読み込み
function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  
  if (!fs.existsSync(ENV_FILE)) {
    return env;
  }
  
  const content = fs.readFileSync(ENV_FILE, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex !== -1) {
        const key = trimmed.substring(0, eqIndex).trim();
        let value = trimmed.substring(eqIndex + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))) {
          value = value.slice(1, -1);
        }
        env[key] = value;
      }
    }
  }
  
  return env;
}

// .env.api に保存
function saveEnv(env: Record<string, string>): void {
  const lines: string[] = [
    '# X Marketing Engine - API Keys & Secrets',
    '# Generated by settings server',
    '',
    '# X (Twitter) Login Credentials',
  ];
  
  if (env.X_USERNAME) lines.push(`X_USERNAME=${env.X_USERNAME}`);
  if (env.X_PASSWORD) lines.push(`X_PASSWORD=${env.X_PASSWORD}`);
  
  lines.push('', '# X (Twitter) API Credentials');
  if (env.X_API_KEY) lines.push(`X_API_KEY=${env.X_API_KEY}`);
  if (env.X_API_SECRET) lines.push(`X_API_SECRET=${env.X_API_SECRET}`);
  if (env.X_ACCESS_TOKEN) lines.push(`X_ACCESS_TOKEN=${env.X_ACCESS_TOKEN}`);
  if (env.X_ACCESS_SECRET) lines.push(`X_ACCESS_SECRET=${env.X_ACCESS_SECRET}`);
  if (env.X_BEARER_TOKEN) lines.push(`X_BEARER_TOKEN=${env.X_BEARER_TOKEN}`);
  
  lines.push('', '# AI API Keys');
  if (env.OPENAI_API_KEY) lines.push(`OPENAI_API_KEY=${env.OPENAI_API_KEY}`);
  if (env.GROK_API_KEY) lines.push(`GROK_API_KEY=${env.GROK_API_KEY}`);
  if (env.GOOGLE_AI_API_KEY) lines.push(`GOOGLE_AI_API_KEY=${env.GOOGLE_AI_API_KEY}`);
  
  lines.push('');
  
  fs.writeFileSync(ENV_FILE, lines.join('\n'));
  console.log('✅ .env.api を保存しました');
}

// GitHub Secrets に同期
function syncToGitHub(env: Record<string, string>): { success: string[]; failed: string[] } {
  const success: string[] = [];
  const failed: string[] = [];
  
  // X_USERNAME と X_PASSWORD は GitHub Secrets に追加
  // その他はすでに設定されているものを更新
  const keysToSync = SECRET_KEYS.filter(key => env[key]);
  
  for (const key of keysToSync) {
    try {
      execSync(`gh secret set ${key} --body "${env[key]}"`, {
        cwd: PROJECT_ROOT,
        stdio: 'pipe'
      });
      success.push(key);
      console.log(`  ✅ ${key}`);
    } catch (error) {
      failed.push(key);
      console.log(`  ❌ ${key}`);
    }
  }
  
  return { success, failed };
}

// CORS ヘッダー
function setCorsHeaders(res: http.ServerResponse): void {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

// リクエストハンドラ
function handleRequest(req: http.IncomingMessage, res: http.ServerResponse): void {
  setCorsHeaders(res);
  
  // OPTIONS (CORS preflight)
  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }
  
  const url = req.url || '/';
  
  // GET /api/settings - 現在の設定を取得
  if (req.method === 'GET' && url === '/api/settings') {
    const env = loadEnv();
    
    // パスワードはマスク
    const masked: Record<string, string> = {};
    for (const key of SECRET_KEYS) {
      if (env[key]) {
        if (key.includes('PASSWORD') || key.includes('SECRET') || key.includes('KEY') || key.includes('TOKEN')) {
          // 最後の4文字以外をマスク
          const val = env[key];
          masked[key] = val.length > 4 ? '*'.repeat(val.length - 4) + val.slice(-4) : '****';
        } else {
          masked[key] = env[key];
        }
      } else {
        masked[key] = '';
      }
    }
    
    // 設定済みかどうかのフラグも返す
    const configured: Record<string, boolean> = {};
    for (const key of SECRET_KEYS) {
      configured[key] = !!env[key];
    }
    
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ masked, configured }));
    return;
  }
  
  // POST /api/settings - 設定を保存
  if (req.method === 'POST' && url === '/api/settings') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try {
        const newSettings = JSON.parse(body) as Record<string, string>;
        
        // 既存の設定を読み込み
        const env = loadEnv();
        
        // 新しい設定をマージ（空でない値のみ）
        for (const [key, value] of Object.entries(newSettings)) {
          if (SECRET_KEYS.includes(key) && value && !value.startsWith('*')) {
            env[key] = value;
          }
        }
        
        // .env.api に保存
        saveEnv(env);
        
        // GitHub Secrets に同期
        console.log('\n📤 GitHub Secrets に同期中...');
        const { success, failed } = syncToGitHub(env);
        
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          message: '設定を保存しました',
          github_sync: {
            success: success.length,
            failed: failed.length,
            details: { success, failed }
          }
        }));
      } catch (error: any) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: error.message }));
      }
    });
    return;
  }
  
  // 404
  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
}

// サーバー起動
const server = http.createServer(handleRequest);

server.listen(PORT, () => {
  console.log(`
🔧 設定サーバー起動
================================
URL: http://localhost:${PORT}

エンドポイント:
  GET  /api/settings  - 現在の設定を取得
  POST /api/settings  - 設定を保存

ダッシュボードの設定画面から操作できます。
`);
});
